[[constraint]]
  name = "github.com/devopsfaith/krakend"
  branch = "0.5-dev"

[[constraint]]
  branch = "master"
  name = "github.com/devopsfaith/krakend-viper"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/rcrowley/go-metrics"

[prune]
  go-tests = true
  unused-packages = true
